package llm

import (
	"context"
	"strings"
)

type MockClient struct {
	Model string
}

func (m MockClient) Name() string {
	if m.Model == "" {
		return "mock"
	}
	return "mock:" + m.Model
}

func (m MockClient) Complete(_ context.Context, messages []Message, _ CompleteOptions) (string, Usage, error) {
	prompt := ""
	if len(messages) > 0 {
		prompt = messages[len(messages)-1].Content
	}
	prompt = strings.ToLower(prompt)

	if strings.Contains(prompt, "localized") || strings.Contains(prompt, "translation") {
		return "Demo localized script:\n1. Hook the audience in the first three seconds.\n2. Keep every sentence short for dubbing.\n3. End with a clear action that matches the platform.", Usage{InputTokens: 180, OutputTokens: 56, TotalTokens: 236}, nil
	}

	if strings.Contains(prompt, "content pack") || strings.Contains(prompt, "titles") {
		return "Titles:\n- Turn Long Meetings into Clear AI Notes\n- Your Meeting Summary, Ready Before You Leave\nCaptions:\n- Ship meeting notes faster with an AI workflow built for busy teams.", Usage{InputTokens: 160, OutputTokens: 44, TotalTokens: 204}, nil
	}

	return "Demo response generated by MediaFlow mock provider.", Usage{InputTokens: 64, OutputTokens: 24, TotalTokens: 88}, nil
}
